name: WeHandU
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "WeHandU by opencarecc"
tagline: "This is the website for WeHandU project by opencarecc"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"

# Facebook OpenGraph stuff
opengraph:
  title: "WeHandU by opencarecc"
  url: "http://opencarecc.github.io/wehandu/"
  description: "This is the website for WeHandU project by opencarecc"
  image_url: "http://opencarecc.github.io/wehandu/assets/OC-Logo-socials.png"

# Twitter Card stuff
twitter:
  site: "WeHandU by opencarecc"
  title: "WeHandU by opencarecc"
  description: "This is the website for WeHandU project by opencarecc"
  creator: "opencarecc"
  domain: "http://opencarecc.github.io/wehandu/"
  image_url: "http://opencarecc.github.io/wehandu/assets/OC-Logo-socials.png"
